Update new_package_request.yml

diff --git a/.github/workflows/new_package_request.yml b/.github/workflows/new_package_request.yml
--- a/.github/workflows/new_package_request.yml
+++ b/.github/workflows/new_package_request.yml
@@ -31,4 +31,9 @@ jobs:
           manifest=$(<manifest.json) &&
           wget https://raw.githubusercontent.com/Snapkg/testing/main/new_package_manifest_schema.json -O manifest_schema.json &&
           cat manifest.json &&
-          ajv -s ./manifest_schema.json -d ./manifest.json > /dev/null 2> validation_error.txt ; if [ $? -ne 0 ] && [ -s validation_error.txt ]; then echo "Validation error:"; cat validation_error.txt; fi
+          if ! (ajv -s ./manifest_schema.json -d ./manifest.json > /dev/null 2> validation_error.txt); then
+            if [ -s validation_error.txt ]; then
+              echo "Validation error:"
+              cat validation_error.txt
+            fi
+          fi
